language: node_js

install: npm install
script: npm run build
deploy:
  provider: script
  script: tools/deploy.sh
  on:
    branch: master
    
branches:
  only:
  - master

# Need to configure env variables in Travis CI settings
# https://travis-ci.org/DavidBruant/autour-de-moi/settings or equivalent:
# * GH_TOKEN : personal access token with read/write access to the repo
